#!/bin/bash:
#PBS -l nodes=8:ppn=16
#PBS -l walltime=2:00:00
#PBS -j oe
#PBS -V
#PBS -N IPythonMPI0

cd /home/rjackson/cmdv-rrm-anl/code
source activate python2
ipcluster start --n=128 --profile=mpi0 &
ipython berr_mass_dealiasing_composite.py --profile=mpi0
